# Generated by Django 3.1.4 on 2021-02-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_assign_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftname', models.CharField(default='', max_length=50)),
                ('ltname', models.CharField(default='', max_length=50)),
                ('role_name', models.CharField(default='', max_length=50)),
                ('rights_name', models.CharField(default='', max_length=50)),
                ('rights_detail', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(default='', max_length=50)),
                ('rdetail', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='', max_length=50)),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=200)),
                ('created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users_Rights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(default=0)),
                ('right_name', models.CharField(default='', max_length=50)),
                ('right_detail', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
