# Generated by Django 3.1.4 on 2021-02-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_assign_role',
            name='rights_detail',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user_assign_role',
            name='rights_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='users_rights',
            name='right_detail',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='users_rights',
            name='right_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
