# Generated by Django 3.1.4 on 2021-02-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210208_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_assign_role',
            name='rights_detail',
        ),
        migrations.RemoveField(
            model_name='user_assign_role',
            name='rights_name',
        ),
        migrations.AddField(
            model_name='user_assign_role',
            name='uname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users_rights',
            name='uname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
